---
inventory:
  plugin: SimpleInventory
  options:
    host_file: inventory/hosts.yaml
    group_file: inventory/groups.yaml

runner:
    plugin: threaded
    options:
        num_workers: 128

logging:
  level: INFO
  to_console: True

netmiko:
  extras:
    netmiko_protocol: telnet
    netmiko_port: 23