---
all:
  platform: cisco_ios

rack1:
  platform: cisco_ios

rack2:
  platform: cisco_ios

router:
  platform: cisco_ios

switch:
  platform: cisco_ios

core-switch:
  platform: cisco_ios

access-switch:
  platform: cisco_ios

router-a:
  platform: cisco_ios
core-switch-a:
  platform: cisco_ios
access-switch-a:
  platform: cisco_ios

router-b:
  platform: cisco_ios
core-switch-b:
  platform: cisco_ios
access-switch-b:
  platform: cisco_ios

router-c:
  platform: cisco_ios
core-switch-c:
  platform: cisco_ios
access-switch-c:
  platform: cisco_ios

router-d:
  platform: cisco_ios
core-switch-d:
  platform: cisco_ios
access-switch-d:
  platform: cisco_ios

router-e:
  platform: cisco_ios
core-switch-e:
  platform: cisco_ios
access-switch-e:
  platform: cisco_ios

router-f:
  platform: cisco_ios
core-switch-f:
  platform: cisco_ios
access-switch-f:
  platform: cisco_ios